language: perl
perl:
  - "5.20"
os: linux

install:
  - curl -L http://cpanmin.us | perl - --self-upgrade
  - cpanm LWP::UserAgent
  - cpanm URI::Find::UTF8
  - cpanm LWP::Protocol::https

script:
  - ./url_checker.pl
