language: minimal
os: linux

install:
  - docker build -t url_checker .
  - git clone https://github.com/EbookFoundation/free-programming-books.git /tmp/workdir/fpb

script:
  - docker run -v /tmp/workdir/fpb:/tmp/fpb -it url_checker $INPUT

matrix:
  include:
    - env: INPUT=free-programming-books.md
    - env: INPUT=free-programming-books-*.md
